#!/bin/bash
# check if the file exists
if [ ! -e /sys/class/backlight/acpi_video0/actual_brightness ]
	then
		exit
fi

brightness=$(cat /sys/class/backlight/acpi_video0/actual_brightness)
maxbright=$(cat /sys/class/backlight/acpi_video0/max_brightness)
percent=$(($brightness * 100 / $maxbright))

echo $percent%
echo $percent%
