#!/bin/bash
# check if the file exists
if [ ! -e /sys/class/backlight/intel_backlight/brightness ]
	then
		exit
fi

BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
MAXBRIGHT=$(cat /sys/class/backlight/intel_backlight/max_brightness)
PERCENT=$(($BRIGHTNESS * 100 / $MAXBRIGHT))

echo $PERCENT%
echo $PERCENT%
